return {
    introcar = function(cutscene)
        local kris = Game.world.player
        local toriel = cutscene:getCharacter("toriel")
        cutscene:wait(cutscene:walkToSpeed(kris, 322, 480, 5))
        cutscene:wait(cutscene:walkToSpeed(kris, 430, 480, 5))
        cutscene:wait(0.25)
        cutscene:setSpeaker(toriel)
        cutscene:text("* Ah,[wait:5] there you are!", "smile")
        cutscene:text("* We may still be able to make it![wait:5] Let us hurry!", "smile")

        -- TODO toriel should have her dialogue as they're walking here, not fully in the car
        cutscene:walkToSpeed(kris, 500, 480)
        cutscene:wait(cutscene:walkToSpeed(toriel, 580, 480))
        cutscene:walkToSpeed(kris, 500, 380)
        cutscene:wait(cutscene:walkToSpeed(toriel, 580, 380))
        -- HACK make player and toriel invisible
        cutscene:setSprite(kris, "")
        cutscene:setSprite(toriel, "")
        cutscene:detachCamera()
        cutscene:panToSpeed(541, 280)
        cutscene:setTextboxTop(true)

        cutscene:wait(1)
        local car = cutscene:getCharacter("torcar")
        cutscene:setAnimation(car, "idle")
        Game.world:transitionMusic("introcar")
        local txtopts = { ["skip"] = false, ["advance"] = false }
        cutscene:text("* " .. Game:getPartyMember("kris"):getName() .. "...[wait:5] It's a beautiful day outside,[wait:5] is it not?", txtopts)
        cutscene:wait(4.5)
        cutscene:text("* On days like these,[wait:5] you and Asriel would play catch for hours.", txtopts)
        cutscene:wait(4.5)
        cutscene:text("* Just a few more days until he is back from college.", txtopts)
        cutscene:wait(4.5)
        cutscene:panToSpeed(541, 650, 3)
        car:resetSprite()
        car:walkToSpeed(541, 600, 4, "left", false, function()
            car:walkToSpeed(340, 600, 4, "down", false, function()
                car:walkToSpeed(340, 1000, 4)
            end )
        end )
        cutscene:text("* I wonder how he must feel,[wait:5] returning to such a small,[wait:5] quaint town like this...", txtopts)
        cutscene:wait(5)
        cutscene:closeText()
        cutscene:wait(2)
        cutscene:after(function()
            cutscene:loadMap("town_residential", 0, 0)
            Game.world:startCutscene("town_residential.introcar2")
        end )
    end,
}
