-- NOTE: Music doesn't play when selected from debug menu, play using Mod:playLegend()
---@param cutscene LegendCutscene
return function(cutscene)
    local panel = cutscene:slide("cutscenes/legend/panel1")
    panel:setScale(2, 2)
    panel.x = 10
    cutscene:setSpeed(1/2)
    cutscene:text("A legend, [wait:10]old as the\nearth wherein we abide,", "middle_bottom")
    cutscene:musicWait(5.125)
    cutscene:removeText()
    cutscene:text("A tale, [wait:10]told under the\nstars that guide.", "middle_bottom")
    cutscene:musicWait(10.25)
    cutscene:removeText()
    cutscene:text("A legend\nof dark,", "left_bottom")
    cutscene:text("A tale\nof dreams,", "text_prince")
    cutscene:musicWait(12.8)
    cutscene:removeText()
    cutscene:text("A legend\nof light.", "left_bottom")
    cutscene:text("A tale\nof hope.", "text_prince")
    cutscene:musicWait(15.4)
    cutscene:removeText()
    cutscene:text("The legend of Delta Rune\n[wait:10]tells our plight.", "middle_bottom")
    cutscene:musicWait(20.5)
    cutscene:removeText()
end
